from django.urls import path
from .views import * 


urlpatterns = [
    path('', home, name='home'),

    path('accounts/login/', login_view, name='user_login'),
    path('logout/', logout_view, name='logout'),
    path('users/', users_list, name='users_list'),
    path('users/create/', user_create, name='user_create'),
    path('users/<int:pk>/edit/', user_edit, name='user_edit'),
    path('users/<int:pk>/delete/', user_delete, name='user_delete'),

    path('categories/', category_list, name='category_list'),
    path('categories/add/', category_add, name='category_add'),
    path('categories/<int:pk>/edit/', category_edit, name='category_edit'),
    path('categories/<int:pk>/delete/', category_delete, name='category_delete'),

    path('products/', product_list, name='product_list'),
    path('products/add/', product_add, name='product_add'),
    path('products/<int:pk>/edit/', product_edit, name='product_edit'),
    path('products/<int:pk>/delete/', product_delete, name='product_delete'),
    path('products/price-update/', product_price_update, name='product_price_update'),
    path('products/price-update-ajax/', product_price_update_ajax, name='product_price_update_ajax'),
    
    path('customers/', customer_list, name='customer_list'),
    path('customers/add/', customer_add, name='customer_add'),
    path('customers/<int:pk>/edit/', customer_edit, name='customer_edit'),
    path('customers/<int:pk>/delete/', customer_delete, name='customer_delete'),
    path('customers/<int:pk>/detail/', customer_detail, name='customer_detail'),
    path('customers/<int:customer_pk>/payment/add/', payment_add, name='payment_add'),
    path('customers/payments/<int:pk>/delete/', payment_delete, name='payment_delete'),
    path('customers/payments/', payment_list, name='payment_list'),

    path('suppliers/', supplier_list, name='supplier_list'),
    path('suppliers/add/', supplier_add, name='supplier_add'),
    path('suppliers/<int:pk>/edit/', supplier_edit, name='supplier_edit'),
    path('suppliers/<int:pk>/delete/', supplier_delete, name='supplier_delete'),
    path('suppliers/<int:pk>/detail/', supplier_detail, name='supplier_detail'),
    path('suppliers/<int:supplier_pk>/payment/add/', supplier_payment_add, name='supplier_payment_add'),
    path('suppliers/payments/<int:pk>/delete/', supplier_payment_delete, name='supplier_payment_delete'),
    path('suppliers/payments/', supplier_payment_list, name='supplier_payment_list'),

    path('expense-categories/', expense_category_list, name='expense_category_list'),
    path('expense-categories/add/', expense_category_add, name='expense_category_add'),
    path('expense-categories/<int:pk>/edit/', expense_category_edit, name='expense_category_edit'),
    path('expense-categories/<int:pk>/delete/', expense_category_delete, name='expense_category_delete'),
    path('expenses/', expense_list, name='expense_list'),
    path('expenses/add/', expense_add, name='expense_add'),
    path('expenses/<int:pk>/edit/', expense_edit, name='expense_edit'),
    path('expenses/<int:pk>/delete/', expense_delete, name='expense_delete'),
    path('expenses/<int:pk>/detail/', expense_detail, name='expense_detail'),
  
    path('inventory/', inventory_list, name='inventory_list'),
    path('inventory/<int:product_pk>/damage/', inventory_damage, name='inventory_damage'),
    path('inventory/<int:product_pk>/gift/', inventory_gift, name='inventory_gift'),
    path('inventory/<int:product_pk>/adjustment/', inventory_stock_adjustment, name='inventory_stock_adjustment'),
    path('inventory/movements/', inventory_movement_list, name='inventory_movement_list'),
    path('inventory/movements/<int:pk>/delete/', inventory_movement_delete, name='inventory_movement_delete'),
    
    path('internal-orders/', internal_order_list, name='internal_order_list'),
    path('internal-orders/add/', internal_order_add, name='internal_order_add'),
    path('internal-orders/<int:pk>/edit/', internal_order_edit, name='internal_order_edit'),
    path('internal-orders/<int:pk>/detail/', internal_order_detail, name='internal_order_detail'),
    path('internal-orders/<int:pk>/confirm/', internal_order_confirm, name='internal_order_confirm'),
    path('internal-orders/<int:pk>/deliver/', internal_order_deliver, name='internal_order_deliver'),
    path('internal-orders/<int:pk>/receive/', internal_order_receive, name='internal_order_receive'),
    path('internal-orders/<int:pk>/cancel/', internal_order_cancel, name='internal_order_cancel'),
    path('internal-orders/<int:pk>/delete/', internal_order_delete, name='internal_order_delete'),
    path('get-product-inventory/<int:product_id>/', get_product_inventory, name='get_product_inventory'),

    path('purchase-invoices/', purchase_invoice_list, name='purchase_invoice_list'),
    path('purchase-invoices/add/', purchase_invoice_add, name='purchase_invoice_add'),
    path('purchase-invoices/<int:pk>/edit/', purchase_invoice_edit, name='purchase_invoice_edit'),
    path('purchase-invoices/<int:pk>/detail/', purchase_invoice_detail, name='purchase_invoice_detail'),
    path('purchase-invoices/<int:pk>/confirm/', purchase_invoice_confirm, name='purchase_invoice_confirm'),
    path('purchase-invoices/<int:pk>/cancel/', purchase_invoice_cancel, name='purchase_invoice_cancel'),
    path('purchase-invoices/<int:pk>/delete/', purchase_invoice_delete, name='purchase_invoice_delete'),
    path('get-product-details/<int:product_id>/', get_product_details, name='get_product_details'),
    
    path('external-commissions/', external_commission_list, name='external_commission_list'),
    path('external-commissions/add/', external_commission_add, name='external_commission_add'),
    path('external-commissions/<int:pk>/edit/', external_commission_edit, name='external_commission_edit'),
    path('external-commissions/<int:pk>/delete/', external_commission_delete, name='external_commission_delete'),
    path('external-orders/', external_order_list, name='external_order_list'),
    path('external-orders/add/', external_order_add, name='external_order_add'),
    path('external-orders/<int:pk>/edit/', external_order_edit, name='external_order_edit'),
    path('external-orders/<int:pk>/detail/', external_order_detail, name='external_order_detail'),
    path('external-orders/<int:pk>/confirm/', external_order_confirm, name='external_order_confirm'),
    path('external-orders/<int:pk>/cancel/', external_order_cancel, name='external_order_cancel'),
    path('external-orders/<int:pk>/delete/', external_order_delete, name='external_order_delete'),
    path('get-commission-rule/', get_commission_rule, name='get_commission_rule'),
    path('external-orders/<int:pk>/deliver/',external_order_deliver, name='external_order_deliver'),
    path('external-orders/<int:pk>/receive/',external_order_receive, name='external_order_receive'),
    path('reports/', reports_dashboard, name='reports_dashboard'),

]
